buildFuture: true
googleAnalytics: "G-XSBR4QLZQR"
languageCode: "en-us"
title: "Code Embers"
baseUrl: https://codeembers.com/
# theme: "cloud-theme"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  footer:
    - name: "Get Involved"
      weight: 1
      url: ""
    - name: "Privacy"
      weight: 2
      url: "/privacy-policy"
    - name: "Cookies"
      weight: 3
      url: "/cookie-policy"
  main:
    - name: "Home"
      weight: 1
      url: "/"
    - name: "About"
      weight: 2
      url: "/about"
    - name: "Episodes"
      weight: 3
      url: "/episode"
    - name: "Hosts"
      weight: 4
      url: "/host"
    # - name: "Guests"
    #   weight: 5
    #   url: "/guest"

module:
  # used for importing theme directly from Github
  imports:
  - path: github.com/FireJuun/cloud-theme

  mounts:
  - source: "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target: "assets/js/bootstrap.bundle.min.js"
  - source: "node_modules/bootstrap/scss"
    target: "assets/sass/bootstrap"
  - source: "./node_modules/@fortawesome/fontawesome-free/scss"
    target: "assets/sass/fontawesome"
  - source: "./node_modules/@fortawesome/fontawesome-free/webfonts"
    target: "static/webfonts"
  - source: content
    target: content
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

params:
  about_logo: "/img/code-embers-logo-square.png"
  author: "John Manning"
  copyright_notice: "Site theme by: [Chris Reddington, 2021](https://www.christianreddington.co.uk). Modified with permission: [MIT license](https://github.com/chrisreddington/cloudwithchris.com/blob/master/LICENSE). Proudly using: [Hugo](https://gohugo.io/)."
  itunes_subscribe: ""
  spotify_subscribe: "https://open.spotify.com/show/6hJOLr15LeXVimTbgJBO7H"
  google_play_subscribe: ""
  stitcher_subscribe: "https://www.stitcher.com/s?fid=628975"
  pocketcasts_subscribe: "https://pca.st/cgnduz1l"
  description: "A podcast created by practicing clinical informaticians who love talking about medicine, technology, and everything bordering or in between. Our content is specifically targeted at prospective or early career clinical informaticians...but is intended to be relevant for developers interested in building for healthcare or clinicians who are just curious about how technology can improve their everyday practice. We are constantly revising our content so please let us know if there is anything you want us to talk about!"
  language_name: "English"
  media_prefix: "https://podcasts.cloudwithchris.com/"
  ogimage: "/img/code-embers-logo-square.png"

  channels:
    apple: ""
    google: ""
    spotify: "https://open.spotify.com/show/6hJOLr15LeXVimTbgJBO7H"

  feed:
    copyright: "Copyright 2021 John Manning, CC BY-SA 4.0" #do not use markdown in this field; it is used in the feed
    itunes_subtitle: "Medicine, Technology, and Everything in Between" #no markdown or HTML
    itunes_author: "Flutter Juun" #no markdown or HTML
    itunes_summary: "A podcast created by practicing clinical informaticians who love talking about medicine, technology, and everything bordering or in between. Our content is specifically targeted at prospective or early career clinical informaticians...but is intended to be relevant for developers interested in building for healthcare or clinicians who are just curious about how technology can improve their everyday practice. We are constantly revising our content so please let us know if there is anything you want us to talk about!"
    itunes_owner_name: "Flutter Juun"
    itunes_owner_email: "flutter.juun@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image: "https://codeembers.com/img/code-embers-logo-square.png" #fqdn to the image art for your podcast
    itunes_top_category: "Medicine"
    itunes_first_sub_category: "Technology"
    itunes_second_sub_category: "Careers"
    language: "en-us"
    explicit: "no"
  
  keywords:
  - code embers
  - codeembers
  - koi pond
  - koi ponds
  - data lakes
  - koi pond elevator pitch
  - clinical informatics
  - clinical informatics fellowship
  - ci fellowship
  - informatics fellowship
  - medical informatics
  - health informatics
  - health technology
  - innovation
  - knowledge operations innovation
  - health tech
  - informatician
  - informaticist
  - physician informatician
  - physician informaticist
  - fellowship
  - healthcare data
  - entrepreneurship
  - interoperability
  - FHIR-FLI
  - FHIR
  - fast healthcare interoperability resources
  - ACIF
  - AMIA's Clinical Informatics Fellows
  - AMIA
  - American Medical Informatics Association
  - PINA
  - Physicians in AMIA
  - flutter juun
  - embers


  social:
    facebook: ""
    github: "firejuun/code-embers-website"
    twitter: "DrJuun"
    # twitter_domain: "" # This domain shows in twitter cards as "View on `twitter_domain`"
    youtube: "FlutterJuun"

privacy:
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: true
    useSessionStorage: false

taxonomies:
  tag: "tags"
